[package]
name = "mb-reloaded"
version = "0.1.0"
authors = ["Ivan Dubrov <dubrov.ivan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.31"
thiserror = "1.0.18"
sdl2 = "0.34.0"
structopt = "0.3.14"

[workspace]
members = [
    ".",
    "tools"
]
