[package]
name = "mb-reloaded-tools"
version = "0.1.0"
authors = ["Ivan Dubrov <dubrov.ivan@gmail.com>"]
edition = "2018"

[dependencies]
mb-reloaded = { path = ".." }
anyhow = "1.0.65"
png = "0.17.6"
rand = "0.8.5"
structopt = "0.3.26"
thiserror = "1.0.37"