[package]
name = "mb-sdl2-effects"
version = "0.1.0"
authors = ["Ivan Dubrov <dubrov.ivan@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.71"
sdl2 = { version = "0.34.0", features = ["mixer"] }
sdl2-sys = { version = "0.34.0", features = ["mixer"] }
once_cell = "1.4.0"